### ISSUE TITLE
Create an optimized Dockerfile for Next js app router

### ISSUE THREAD

**Issue by akadeepesh** [akadeepesh/LoanManagement#4]
Please use multi staging, standalone application, alpine and best practices.

**Comment by rohits-web03** [comment]
Hii @akadeepesh, I would like to work on this issue. 
Would appreciate if you could assign me.

**Comment by akadeepesh** [comment]
Sure @rohits-web03 go on!

**Comment by rohits-web03** [comment]
Hey @akadeepesh , I'm almost done 
Will be making the pr within a couple of hours as I am a bit occupied with something else now
Can you assign me? (Since you unassigned me :( )

**Comment by akadeepesh** [comment]
Yeah sure @rohits-web03, I unassigned you because of the inactivity. Assigning you back to the issue.
